#docker-compose.ymlのバージョン
version: '3.8'
volumes:
  docker-volume:

#webサーバー、アプリケーション、DBコンテナの設定
services:
  web:
    build: ./docker/nginx
    ports:
      - '8000:80'
    depends_on:
      - app
    volumes:
      - .:/app
  app:
    build: ./docker/php
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${DB_TZ}
    volumes:
      - docker-volume:/var/lib/mysql
